language: node_js
node_js:
- '9'
addons:
  ssh_known_hosts: linux.cs.odu.edu
before_install:
  - openssl aes-256-cbc -K $encrypted_5010aab3bf34_key -iv $encrypted_5010aab3bf34_iv
    -in id_rsa.enc -out ./id_rsa -d
  - ssh-add ./deploy_key
deploy:
  provider: script
  skip_cleanup: true
  script: -Pavqr -e "ssh -i ~/.ssh/id_rsa" $TRAVIS_BUILD_DIR/<dir> 410yello@linux.cs.odu.edu:~/secure_html/temp
  on:
    branch: master
