language: node_js
node_js:
- '9'
addons:
  ssh_known_hosts: linux.cs.odu.edu
before_install:
  - openssl aes-256-cbc -K $encrypted_5010aab3bf34_key -iv $encrypted_5010aab3bf34_iv -in id_rsa.enc -out ./id_rsa -d
  - echo $TRAVIS_BUILD_DIR
  - eval "$(ssh-agent -s)"
  - chmod 600 ./id_rsa
  - ssh-add ./id_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -Pavqrd -e "ssh -i ./id_rsa" $TRAVIS_BUILD_DIR/ 410yello@linux.cs.odu.edu:~/secure_html/
  on:
    branch: master
